server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: monitoring-service
          uri: lb://MONITORING-SERVICE
          predicates:
            - Path=/api/monitoring/**

  # Security properties have been removed for stateless routing proxy

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
