spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "https://client-uptime-frontend.vercel.app"
              - "https://*.vercel.app"
              - "http://localhost:5173"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: monitoring-service
          uri: https://sentinel-monitoring-latest.onrender.com
          predicates:
            - Path=/api/monitoring/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
            - PreserveHostHeader

server:
  forward-headers-strategy: framework
  port: ${PORT:8080}
  netty:
    connection-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}