server:
  port: ${PORT}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - https://client-uptime-frontend.vercel.app
              - https://*.vercel.app
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: monitoring-service
          uri: https://sentinel-monitoring-latest.onrender.com
          predicates:
            - Path=/api/monitoring/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true