server:
  address: 0.0.0.0
  port: ${PORT:10000}
  forward-headers-strategy: framework

spring:
  application:
    name: monitoring-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}

google:
  client-id: ${GOOGLE_CLIENT_ID}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    instance-id: ${spring.application.name}:${random.value}

stripe:
  api:
    key: ${STRIPE_API_KEY:}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:}